version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '6000:5432'
    expose:
      - 6000
    environment:
      POSTGRES_DB: chatnow
      POSTGRES_PASSWORD: 123456789
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: hai@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
volumes:
  db_data:
