version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 123456789
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hai@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789